---

- hosts: hqvca.secnetwork.org
  gather_facts: no

  collections:
    - community.vmware

  vars:
  create_dvs_portgroup:
    - portgroup_name: VLAN_011-Management
      switch_name: hqdvsw1
      vlan_id: 11
    - portgroup_name: VLAN_015-Admins
      switch_name: hqdvsw1
      vlan_id: 15
    - portgroup_name: VLAN_021-vManagement
      switch_name: hqdvsw1
      vlan_id: 21
    - portgroup_name: VLAN_022-vMotion
      switch_name: hqdvsw2
      vlan_id: 22
    - portgroup_name: VLAN_023-vSAN
      switch_name: hqdvsw2
      vlan_id: 23
    - portgroup_name: VLAN_031-PDC
      switch_name: hqdvsw1
      vlan_id: 31
    - portgroup_name: VLAN_032-PKI
      switch_name: hqdvsw1
      vlan_id: 32
    - portgroup_name: VLAN_033-NAC
      switch_name: hqdvsw1
      vlan_id: 33
    - portgroup_name: VLAN_034-SSO
      switch_name: hqdvsw1
      vlan_id: 34
    - portgroup_name: VLAN_041-LOG
      switch_name: hqdvsw1
      vlan_id: 41
    - portgroup_name: VLAN_042-VAS
      switch_name: hqdvsw1
      vlan_id: 42
    - portgroup_name: VLAN_043-MON
      switch_name: hqdvsw1
      vlan_id: 43
    - portgroup_name: VLAN_044-NVR
      switch_name: hqdvsw1
      vlan_id: 44
    - portgroup_name: VLAN_051-SRV
      switch_name: hqdvsw1
      vlan_id: 51
    - portgroup_name: VLAN_091-DMZ_Frontend
      switch_name: hqdvsw1
      vlan_id: 91
    - portgroup_name: VLAN_095-DMZ_Backend
      switch_name: hqdvsw1
      vlan_id: 95
    - portgroup_name: VLAN_141-IOT
      switch_name: hqdvsw1
      vlan_id: 141

  tasks:
    - name: Add vCenter license
      community.vmware.vcenter_license:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        license: '{{ lic_vcenter_8 }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Create Datacenter
      community.vmware.vmware_datacenter:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter_name: '{{ datacenter_name }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Create Management Cluster
      community.vmware.vmware_cluster:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: Management
        validate_certs: false
      delegate_to: localhost

    - name: Create Infrastructure Cluster
      community.vmware.vmware_cluster:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: Infrastructure
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH1 ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter: '{{ datacenter_name }}'
        cluster: Management
        esxi_hostname: '{{ esxi_host_1 }}'
        esxi_username: '{{ esxi_username }}'
        esxi_password: '{{ esxi_password }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH1 ESXi license and assign to the ESXi host
      community.vmware.vcenter_license:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        esxi_hostname: '{{ esxi_host_1 }}'
        license: '{{ lic_esxi_6 }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH11 ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter: '{{ datacenter_name }}'
        cluster: Infrastructure
        esxi_hostname: '{{ esxi_host_11 }}'
        esxi_username: '{{ esxi_username }}'
        esxi_password: '{{ esxi_password }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH12 ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter: '{{ datacenter_name }}'
        cluster: Infrastructure
        esxi_hostname: '{{ esxi_host_12 }}'
        esxi_username: '{{ esxi_username }}'
        esxi_password: '{{ esxi_password }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH13 ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter: '{{ datacenter_name }}'
        cluster: Infrastructure
        esxi_hostname: '{{ esxi_host_13 }}'
        esxi_username: '{{ esxi_username }}'
        esxi_password: '{{ esxi_password }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH14 ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter: '{{ datacenter_name }}'
        cluster: Infrastructure
        esxi_hostname: '{{ esxi_host_14 }}'
        esxi_username: '{{ esxi_username }}'
        esxi_password: '{{ esxi_password }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH11 ESXi license
      community.vmware.vcenter_license:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        esxi_hostname: '{{ esxi_host_11 }}'
        license: '{{ lic_esxi_8 }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH12 ESXi license
      community.vmware.vcenter_license:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        esxi_hostname: '{{ esxi_host_12 }}'
        license: '{{ lic_esxi_8 }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH13 ESXi license
      community.vmware.vcenter_license:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        esxi_hostname: '{{ esxi_host_13 }}'
        license: '{{ lic_esxi_8 }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Add HQVH14 ESXi license
      community.vmware.vcenter_license:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        esxi_hostname: '{{ esxi_host_14 }}'
        license: '{{ lic_esxi_8 }}'
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Set NTP servers Management Cluster
      community.vmware.vmware_host_ntp:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        cluster_name: Management
        state: present
        validate_certs: false
        ntp_servers:
            - 0.pool.ntp.org
            - 1.pool.ntp.org
      delegate_to: localhost

    - name: Set NTP servers Infrastructure Cluster
      community.vmware.vmware_host_ntp:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        cluster_name: Infrastructure
        state: present
        validate_certs: false
        ntp_servers:
            - 0.pool.ntp.org
            - 1.pool.ntp.org
      delegate_to: localhost

    - name: Configure DNS servers Management cluster
      community.vmware.vmware_host_dns:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        cluster_name: Management
        type: static
        domain: secnetwork.org
        dns_servers:
          - 10.0.31.11
          - 10.0.31.12
        search_domains:
          - secnetwork.org
        validate_certs: false
      delegate_to: localhost

    - name: Configure DNS servers Infrastructure cluster
      community.vmware.vmware_host_dns:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        cluster_name: Infrastructure
        type: static
        domain: secnetwork.org
        dns_servers:
          - 10.0.31.11
          - 10.0.31.12
        search_domains:
          - secnetwork.org
        validate_certs: false
      delegate_to: localhost

    - name: Create Primary dvSwitch
      community.vmware.vmware_dvswitch:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter: '{{ datacenter_name }}'
        switch: hqdvsw1
        version: 6.6.0
        mtu: 9000
        uplink_quantity: 4
        uplink_prefix: 'UPLINK_'
        discovery_protocol: lldp
        discovery_operation: both
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Create Storage dvSwitch
      community.vmware.vmware_dvswitch:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        datacenter: '{{ datacenter_name }}'
        switch: hqdvsw2
        version: 8.0.0
        mtu: 9000
        uplink_quantity: 2
        uplink_prefix: 'UPLINK_'
        discovery_protocol: lldp
        discovery_operation: both
        state: present
        validate_certs: false
      delegate_to: localhost

    - name: Create VLAN Portgroup
      community.vmware.vmware_dvs_portgroup:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        portgroup_name: '{{ item.portgroup_name }}'
        switch_name: '{{ item.switch_name }}'
        vlan_id: '{{ item.vlan_id }}'
        num_ports: 24
        port_binding: static
        state: present
      delegate_to: localhost
      with_items: '{{ create_dvs_portgroup }}'

    - name: Create VLAN Trunk Portgroup
      community.vmware.vmware_dvs_portgroup:
        hostname: '{{ vca_host }}'
        username: '{{ vca_username }}'
        password: '{{ vca_password }}'
        portgroup_name: TRUNK_DOCKER
        switch_name: hqdvsw1
        vlan_id: 31-34, 41-44, 51, 91, 95, 141
        vlan_trunk: True
        num_ports: 24
        port_binding: static
        state: present
      delegate_to: localhost
