---

- hosts: 10.0.21.101
  gather_facts: no

  collections:
    - community.vmware

  tasks:
    - name: Configure DNS for an ESXi host
      vmware_host_dns:
        hostname: '{{ esxi_host_1 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        type: static
        host_name: 'hqvh1'
        domain: secnetwork.org
        dns_servers:
          - 10.0.31.11
          - 10.0.31.12
        search_domains:
          - secnetwork.org
      delegate_to: localhost

    - name: Remove VM Network Portgroup
      vmware_portgroup:
        hostname: '{{ esxi_host_1 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        hosts: [hqvh1.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "VM Network"
        state: absent
      delegate_to: localhost

    - name: Remove VM Network Portgroup
      vmware_portgroup:
        hostname: '{{ esxi_host_11 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        hosts: [hqvh11.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "VM Network"
        state: absent
      delegate_to: localhost

    - name: Remove VM Network Portgroup
      vmware_portgroup:
        hostname: '{{ esxi_host_12 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        hosts: [hqvh12.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "VM Network"
        state: absent
      delegate_to: localhost

    - name: Remove VM Network Portgroup
      vmware_portgroup:
        hostname: '{{ esxi_host_13 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        hosts: [hqvh13.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "VM Network"
        state: absent
      delegate_to: localhost

    - name: Remove VM Network Portgroup
      vmware_portgroup:
        hostname: '{{ esxi_host_14 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        hosts: [hqvh14.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "VM Network"
        state: absent
      delegate_to: localhost

    - name: Add vManagement Portgroup
      community.vmware.vmware_portgroup:
        hostname: '{{ esxi_host_1 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        hosts: [hqvh1.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "vManagement"
        vlan_id: "21"
      delegate_to: localhost

    - name: Add PDC Portgroup
      community.vmware.vmware_portgroup:
        hostname: '{{ esxi_host_1 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        hosts: [hqvh1.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "PDC"
        vlan_id: "31"
      delegate_to: localhost

    - name: Add Servers Portgroup
      community.vmware.vmware_portgroup:
        hostname: '{{ esxi_host_1 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        hosts: [hqvh1.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "Servers"
        vlan_id: "51"
      delegate_to: localhost