---

- hosts: 10.0.21.205
  gather_facts: no

  collections:
    - community.vmware

  tasks:
    - name: Configure DNS for an ESXi host
      vmware_host_dns:
        hostname: '{{ esxi_host_5 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        type: static
        host_name: 'hqvh5'
        domain: secnetwork.org
        dns_servers:
          - 1.1.1.1
          - 8.8.8.8
        search_domains:
          - secnetwork.org
      delegate_to: localhost

    - name: Remove Portgroup
      vmware_portgroup:
        hostname: '{{ esxi_host_5 }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        cluster_name: [hqvh5.secnetwork.org]
        switch: "{{ esxi_vswitch }}"
        portgroup: "VM Network"
        state: absent
      delegate_to: localhost