---
- name: Registering Hosts
  hosts: docker
  gather_facts: yes
  become: true

  vars_prompt:
  - name: "bind_password"
    prompt: "Password for yatesj-admin"
    private: yes

  tasks:
    - name: let the register begin
      expect:
        command: cmk-update-agent register -v -H '{{ ansible_hostname }}'.secnetwork.org  -U yatesj-admin
        responses:
          Password for *: "{{ bind_password }}"
      when: result.stdout == "" 


