---

- import_playbook: device_setup.yml
- import_playbook: object_tags.yml
- import_playbook: object_address.yml
- import_playbook: network_zones.yml
- import_playbook: network_interfaces.yml
- import_playbook: network_vr.yml
- import_playbook: policy_nat.yml
- import_playbook: policy_security_99_deny_all_traffic.yml
- import_playbook: policy_security_01_unauthorized_traffic.yml
- import_playbook: policy_security_02_firewall_services.yml
- import_playbook: policy_security_03_public_services.yml
- import_playbook: policy_security_90_tmp_internet_access.yml