---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_zones:
      - zone_name: "L2-WAN"
        zone_mode: layer2
        zone_userid: no

      - zone_name: "L2-LAN"
        zone_mode: layer2
        zone_userid: no

      - zone_name: "L3-WAN"
        zone_mode: layer3
        zone_userid: no

      - zone_name: "{{ zone_mgt }}"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "{{ zone_virt }}"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "{{ zone_auth }}"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "{{ zone_sec }}"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "{{ zone_srv }}"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "{{ zone_dmz }}"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "{{ zone_end }}"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "{{ zone_gst }}"
        zone_mode: layer3
        zone_userid: no

      - zone_name: "{{ zone_prjr }}"
        zone_mode: layer3
        zone_userid: no

      - zone_name: "{{ zone_prjy }}"
        zone_mode: layer3
        zone_userid: no

  tasks:
    - name: Create Zones
      panos_zone:
        provider: '{{ provider }}'
        zone: '{{ item.zone_name }}'
        mode: '{{ item.zone_mode }}'
        enable_userid: '{{ item.zone_userid }}'
      with_items: '{{ create_zones }}'