---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_zones:
      - zone_name: "L2-WAN"
        zone_mode: layer2
        zone_userid: no

      - zone_name: "L2-LAN"
        zone_mode: layer2
        zone_userid: no

      - zone_name: "L3-WAN"
        zone_mode: layer3
        zone_userid: no

      - zone_name: "L3-Management"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "L3-Virtualization"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "L3-Authentication"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "L3-Security"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "L3-DMZ"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "L3-Endpoints"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "L3-Guests"
        zone_mode: layer3
        zone_userid: no

      - zone_name: "L3-Project-R"
        zone_mode: layer3
        zone_userid: no

      - zone_name: "L3-Project-Y"
        zone_mode: layer3
        zone_userid: no

  tasks:
#    - name: Import Credentials from File
#      include_vars: '/root/secnet-ansible/fw'
#      no_log: 'yes'

    - name: Create Zones
      panos_zone:
        provider: '{{ provider }}'
        zone: '{{ item.zone_name }}'
        mode: '{{ item.zone_mode }}'
        enable_userid: '{{ item.zone_userid }}'
      with_items: '{{ create_zones }}'