---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    aggregate_group_name: "ae1"
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_management_profile:
      - create_mgt_profile_name: 'Management'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: yes
        create_mgt_profile_ssh: yes
        create_mgt_profile_snmp: yes
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: no

      - create_mgt_profile_name: 'Default'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: no
        create_mgt_profile_ssh: no
        create_mgt_profile_snmp: no
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: no

      - create_mgt_profile_name: 'Users'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: no
        create_mgt_profile_ssh: no
        create_mgt_profile_snmp: no
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: yes

      - create_mgt_profile_name: 'Internet'
        create_mgt_profile_ping: no
        create_mgt_profile_https: no
        create_mgt_profile_ssh: no
        create_mgt_profile_snmp: no
        create_mgt_profile_response_pages: no
        create_mgt_profile_userid_service: no

    create_aggregate_interface:
      - if_name: "ethernet1/9"
      - if_name: "ethernet1/10"
      - if_name: "ethernet1/11"
      - if_name: "ethernet1/12"
      
    create_vlans:
      - name: '{{ aggregate_group_name }}.11'
        tag: "11"
        enable_dhcp: "false"
        management_profile: 'Management'
        ip: ["10.0.11.1/24"]
        zone_name: "L3-Management"
        comment: "Management"

      - name: '{{ aggregate_group_name }}.15'
        tag: "15"
        enable_dhcp: "false"
        management_profile: 'Management'
        ip: ["10.0.15.1/24"]
        zone_name: "L3-Management"
        comment: "Admins"

      - name: '{{ aggregate_group_name }}.21'
        tag: "21"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.21.1/24"]
        zone_name: "L3-Virtualization"
        comment: "vManagement"

      - name: '{{ aggregate_group_name }}.31'
        tag: "31"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.31.1/24"]
        zone_name: "L3-Authentication"
        comment: "PDC"

      - name: '{{ aggregate_group_name }}.32'
        tag: "32"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.32.1/24"]
        zone_name: "L3-Authentication"
        comment: "PKI"

      - name: '{{ aggregate_group_name }}.33'
        tag: "33"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.33.1/24"]
        zone_name: "L3-Authentication"
        comment: "NAC"

      - name: '{{ aggregate_group_name }}.34'
        tag: "34"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.34.1/24"]
        zone_name: "L3-Authentication"
        comment: "SSO"

      - name: '{{ aggregate_group_name }}.41'
        tag: "41"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.41.1/24"]
        zone_name: "L3-Security"
        comment: "LOG"

      - name: '{{ aggregate_group_name }}.42'
        tag: "42"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.42.1/24"]
        zone_name: "L3-Security"
        comment: "VAS"

      - name: '{{ aggregate_group_name }}.43'
        tag: "43"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.43.1/24"]
        zone_name: "L3-Security"
        comment: "MON"

      - name: '{{ aggregate_group_name }}.44'
        tag: "44"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.44.1/24"]
        zone_name: "L3-Security"
        comment: "NVR"

      - name: '{{ aggregate_group_name }}.51'
        tag: "51"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.51.1/24"]
        zone_name: "L3-Servers"
        comment: "Servers"

      - name: '{{ aggregate_group_name }}.91'
        tag: "91"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.81.1/24"]
        zone_name: "L3-DMZ"
        comment: "Frontend"

      - name: '{{ aggregate_group_name }}.95'
        tag: "95"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.95.1/24"]
        zone_name: "L3-DMZ"
        comment: "Backend"

      - name: '{{ aggregate_group_name }}.111'
        tag: "111"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.111.1/24"]
        zone_name: "L3-Endpoints"
        comment: "Users"

      - name: '{{ aggregate_group_name }}.121'
        tag: "121"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.121.1/24"]
        zone_name: "L3-Endpoints"
        comment: "Printers"

      - name: '{{ aggregate_group_name }}.131'
        tag: "131"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.131.1/24"]
        zone_name: "L3-Endpoints"
        comment: "Phones"

      - name: '{{ aggregate_group_name }}.141'
        tag: "141"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.141.1/24"]
        zone_name: "L3-Endpoints"
        comment: "IOT"

      - name: '{{ aggregate_group_name }}.666'
        tag: "666"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["192.168.1.1/24"]
        zone_name: "L3-Guests"
        comment: "Guests"

  tasks:
    - name: Create Interface Management Profile
      panos_management_profile:
        provider: '{{ provider }}'
        name: '{{ item.create_mgt_profile_name }}'
        ping: '{{ item.create_mgt_profile_ping }}'
        https: '{{ item.create_mgt_profile_https }}'
        ssh: '{{ item.create_mgt_profile_ssh }}'
        snmp: '{{ item.create_mgt_profile_snmp }}'
        response_pages: '{{ item.create_mgt_profile_response_pages }}'
        userid_service: '{{ item.create_mgt_profile_userid_service}}'
      with_items: '{{ create_management_profile }}'

    - name: Creating Aggregate Interface
      panos_aggregate_interface:
        provider: '{{ provider }}'
        if_name: '{{ aggregate_group_name }}'
        mode: "layer3"
        vr_name: "default"
        lacp_enable: "true"
        lacp_mode: "active"

    - name: Configuring Aggregate Interfaces
      panos_interface:
        provider: '{{ provider }}'
        if_name: '{{ item.if_name }}'
        mode: "aggregate-group"
        aggregate_group: '{{ aggregate_group_name }}'
      with_items: '{{ create_aggregate_interface }}'

    - name: Creating Subinterfaces
      panos_l3_subinterface:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        tag: '{{ item.tag }}'
        ip: '{{ item.ip }}'
        zone_name: '{{ item.zone_name }}'
        enable_dhcp: '{{ item.enable_dhcp }}'
        management_profile: '{{ item.management_profile }}'
        comment: '{{ item.comment }}'
      with_items: '{{ create_vlans }}'

    - name: Creating "Project-R" Subinterface
      panos_l3_subinterface:
        provider: '{{ provider }}'
        name: '{{ aggregate_group_name }}.1311'
        tag: "1311"
        ip: ["10.13.11.1/24"]
        zone_name: "Project-R"
        enable_dhcp: "false"
        management_profile: 'Users'
        vr_name: "Project-R"
        comment: "Project-R"

    - name: Creating WAN VLAN
      panos_vlan:
        provider: '{{ provider }}'
        name: 'WAN'

    - name: Configure WAN VLAN Interface
      panos_vlan_interface:
        provider: '{{ provider }}'
        name: "vlan.9000"
        ip: ["96.231.240.210/24"]
        management_profile: "Internet"
        vlan_name: "WAN"
        zone_name: "L3-WAN"
        vr_name: "default"

    - name: Configuring ISP Uplink Interface
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/1"
        mode: "layer2"
        vlan_name: "WAN"
        zone_name: "L2-WAN"

    - name: Configuring L2 LAN INT 2
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/2"
        mode: "layer2"
        vlan_name: "WAN"
        zone_name: "L2-LAN"

    - name: Configuring L2 LAN INT 3
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/3"
        mode: "layer2"
        vlan_name: "WAN"        
        enable_dhcp: false
        zone_name: "L2-LAN"

    - name: Configuring L2 LAN INT 4
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/4"
        mode: "layer2"
        vlan_name: "WAN"        
        enable_dhcp: false
        zone_name: "L2-LAN"