---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    aggregate_group_name: "ae2"
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_management_profile:
      - create_mgt_profile_name: 'Management'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: yes
        create_mgt_profile_ssh: yes
        create_mgt_profile_snmp: yes
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: no
        create_mgt_profile_userid_syslog_listener_ssl: no 
        create_mgt_profile_userid_syslog_listener_udp: no

      - create_mgt_profile_name: 'Default'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: no
        create_mgt_profile_ssh: no
        create_mgt_profile_snmp: no
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: no
        create_mgt_profile_userid_syslog_listener_ssl: no
        create_mgt_profile_userid_syslog_listener_udp: no

      - create_mgt_profile_name: 'Users'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: no
        create_mgt_profile_ssh: no
        create_mgt_profile_snmp: no
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: yes
        create_mgt_profile_userid_syslog_listener_ssl: no
        create_mgt_profile_userid_syslog_listener_udp: no

    create_aggregate_interface:
      - if_name: "ethernet1/9"
      - if_name: "ethernet1/10"

    create_vlans:
      - name: '{{ aggregate_group_name }}.11'
        tag: "11"
        enable_dhcp: "false"
        management_profile: 'Management'
        ip: ["10.0.11.1/24"]
        zone_name: "MGT"

      - name: '{{ aggregate_group_name }}.21'
        tag: "21"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.21.1/24"]
        zone_name: "VRT"

      - name: '{{ aggregate_group_name }}.31'
        tag: "31"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.31.1/24"]
        zone_name: "IDAM"

      - name: '{{ aggregate_group_name }}.32'
        tag: "32"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.32.1/24"]
        zone_name: "IDAM"

      - name: '{{ aggregate_group_name }}.33'
        tag: "33"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.33.1/24"]
        zone_name: "IDAM"

      - name: '{{ aggregate_group_name }}.34'
        tag: "34"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.34.1/24"]
        zone_name: "IDAM"                

      - name: '{{ aggregate_group_name }}.41'
        tag: "41"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.41.1/24"]
        zone_name: "SEC"

      - name: '{{ aggregate_group_name }}.42'
        tag: "42"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.42.1/24"]
        zone_name: "SEC"

      - name: '{{ aggregate_group_name }}.43'
        tag: "43"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.43.1/24"]
        zone_name: "SEC"

      - name: '{{ aggregate_group_name }}.44'
        tag: "44"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.44.1/24"]
        zone_name: "SEC"

      - name: '{{ aggregate_group_name }}.51'
        tag: "51"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.51.1/24"]
        zone_name: "SRV"

      - name: '{{ aggregate_group_name }}.91'
        tag: "91"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.91.1/24"]
        zone_name: "DMZ"

      - name: '{{ aggregate_group_name }}.111'
        tag: "111"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.111.1/24"]
        zone_name: "EPD"

      - name: '{{ aggregate_group_name }}.121'
        tag: "121"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.121.1/24"]
        zone_name: "EPD"

      - name: '{{ aggregate_group_name }}.131'
        tag: "131"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.131.1/24"]
        zone_name: "EPD"

      - name: '{{ aggregate_group_name }}.141'
        tag: "141"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.141.1/24"]
        zone_name: "EPD"

      - name: '{{ aggregate_group_name }}.666'
        tag: "666"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["192.168.1.1/24"]
        zone_name: "GUESTS"   

  tasks:
    - name: Import Credentials from File
      include_vars: '/root/secnet-ansible/fw'
      no_log: 'yes'

    - name: Create Interface Management Profile
      panos_management_profile:
        provider: '{{ provider }}'
        name: '{{ item.create_mgt_profile_name }}'
        ping: '{{ item.create_mgt_profile_ping }}'
        https: '{{ item.create_mgt_profile_https }}'
        ssh: '{{ item.create_mgt_profile_ssh }}'
        snmp: '{{ item.create_mgt_profile_snmp }}'
        response_pages: '{{ item.create_mgt_profile_response_pages }}'
        userid_service: '{{ item.create_mgt_profile_userid_service}}'
        #userid_syslog_listener_ssl: '{{ item.create_mgt_profile_userid_syslog_listener_ssl }}'
        #userid_syslog_listener_udp: '{{ item.create_mgt_profile_userid_syslog_listener_udp }}'
      with_items: '{{ create_management_profile }}'

    - name: Creating Aggregate Interface
      panos_aggregate_interface:
        provider: '{{ provider }}'
        if_name: '{{ aggregate_group_name }}'
        mode: "layer3"
        vr_name: "none"
        lacp_enable: "true"
        lacp_mode: "active"

    - name: Configuring Aggregate Interfaces
      panos_interface:
        provider: '{{ provider }}'
        if_name: '{{ item.if_name }}'
        mode: "aggregate-group"
        aggregate_group: '{{ aggregate_group_name }}'
      with_items: '{{ create_aggregate_interface }}'

    - name: Creating Subinterfaces
      panos_l3_subinterface:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        tag: '{{ item.tag }}'
        ip: '{{ item.ip }}'
        zone_name: '{{ item.zone_name }}'
        enable_dhcp: '{{ item.enable_dhcp }}'
        management_profile: '{{ item.management_profile }}'
      with_items: '{{ create_vlans }}'

    - name: Creating "PROJECT-R" Subinterface
      panos_l3_subinterface:
        provider: '{{ provider }}'
        name: '{{ aggregate_group_name }}.1311'
        tag: "1311"
        ip: ["10.13.11.1/24"]
        zone_name: "PROJECT-R"
        enable_dhcp: "false"
        management_profile: 'Users'
        vr_name: "PROJECT-R"

    - name: Configuring WAN Interface
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/1"
        mode: "layer3"
        ip: ["96.231.240.217/24"]
        enable_dhcp: false
        zone_name: "WAN"
