---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_zones:
      - zone_name: "WAN"
        zone_mode: layer3
        zone_userid: no

      - zone_name: "MGT"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "IDAM"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "SEC"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "DMZ"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "EPD"
        zone_mode: layer3
        zone_userid: yes

      - zone_name: "GUESTS"
        zone_mode: layer3
        zone_userid: no

      - zone_name: "PROJECT-R"
        zone_mode: layer3
        zone_userid: no

  tasks:
    - name: Import Credentials from File
      include_vars: '/root/secnet-ansible/fw'
      no_log: 'yes'

    - name: Create Zones
      panos_zone:
        provider: '{{ provider }}'
        zone: '{{ item.zone_name }}'
        mode: '{{ item.zone_mode }}'
        enable_userid: '{{ item.zone_userid }}'
      with_items: '{{ create_zones }}'