---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

  tasks:
    - name: Import Credentials from File
      include_vars: '/root/secnet-ansible/fw'
      no_log: 'yes'

    - name: Create Virtual Router
      panos_virtual_router:
        provider: '{{ provider }}'
        name: "Project-R"

    - name: Create Default Static Route
      panos_static_route:
        provider: '{{ provider }}'
        name: Default Gateway
        destination: '0.0.0.0/0'
        nexthop: '96.231.240.1'
        nexthop_type: ip-address
        interface: ethernet1/1
