---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_tags:
      - tag_name: "Unauthorized Traffic"
        tag_color: "red"
        tag_comments: "Unauthorized Traffic"

      - tag_name: "Authentication"
        tag_color: "purple"
        tag_comments: "Authentication"

      - tag_name: "DMZ"
        tag_color: "purple"
        tag_comments: "DMZ"
      
      - tag_name: "Endpoints"
        tag_color: "purple"
        tag_comments: "Endpoints"
      
      - tag_name: "Guests"
        tag_color: "purple"
        tag_comments: "Guests"
      
      - tag_name: "Servers"
        tag_color: "purple"
        tag_comments: "Servers"
      
      - tag_name: "Virtualization"
        tag_color: "purple"
        tag_comments: "Virtualization"
      
      - tag_name: "Management"
        tag_color: "purple"
        tag_comments: "Management"
      
      - tag_name: "Security"
        tag_color: "purple"
        tag_comments: "Security"

      - tag_name: "OUTBOUND"
        tag_color: "red"
        tag_comments: "OUTBOUND"

      - tag_name: "INBOUND"
        tag_color: "red"
        tag_comments: "INBOUND"

      - tag_name: "EXTERNAL"
        tag_color: "red"
        tag_comments: "EXTERNAL"
        
      - tag_name: "INTERNAL"
        tag_color: "blue"
        tag_comments: "INTERNAL"

      - tag_name: "WAN"
        tag_color: "red"
        tag_comments: "WAN"

      - tag_name: "Firewall Services"
        tag_color: "blue"
        tag_comments: "Firewall Services"

  tasks:
    - name: Creating Interface Tags
      panos_tag_object:
        provider: '{{ provider }}'
        name: '{{ item.tag_name }}'
        color: '{{ item.tag_color }}'
        comments: '{{ item.tag_comments }}'
      with_items: '{{ create_tags }}'
