---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_tags:
      - tag_name: "SECNET-MGT"
        tag_color: "purple"
        tag_comments: "SECNET-MGT"
      - tag_name: "SECNET-DMZ"
        tag_color: "purple"
        tag_comments: "SECNET-DMZ"
      - tag_name: "SECNET-AAA"
        tag_color: "purple"
        tag_comments: "SECNET-AAA"
      - tag_name: "SECNET-SEC"
        tag_color: "purple"
        tag_comments: "SECNET-SEC"
      - tag_name: "SECNET-SRV"
        tag_color: "purple"
        tag_comments: "SECNET-SRV"
      - tag_name: "SECNET-VRT"
        tag_color: "purple"
        tag_comments: "SECNET-VRT"
      - tag_name: "SECNET-ADM"
        tag_color: "purple"
        tag_comments: "SECNET-ADM"
      - tag_name: "SECNET-USR"
        tag_color: "purple"
        tag_comments: "SECNET-USR"

      - tag_name: "Unauthorized Traffic"
        tag_color: "red"
        tag_comments: "Unauthorized Traffic"
      - tag_name: "OUTBOUND"
        tag_color: "red"
        tag_comments: "OUTBOUND"
      - tag_name: "INBOUND"
        tag_color: "red"
        tag_comments: "INBOUND"
      - tag_name: "EXTERNAL"
        tag_color: "red"
        tag_comments: "EXTERNAL"
      - tag_name: "INTERNAL"
        tag_color: "blue"
        tag_comments: "INTERNAL"
      - tag_name: "WAN"
        tag_color: "red"
        tag_comments: "WAN"

      - tag_name: "Firewall Services"
        tag_color: "blue"
        tag_comments: "Firewall Services"

  tasks:
    - name: Import Credentials from File
      include_vars: '/home/p0001/ansible/fw'
      no_log: 'yes'

    - name: Creating Interface Tags
      panos_tag_object:
        provider: '{{ provider }}'
        name: '{{ item.tag_name }}'
        color: '{{ item.tag_color }}'
        comments: '{{ item.tag_comments }}'
      with_items: '{{ create_tags }}'
