---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_address_object:
      - address_object_name: "SECNET HQ Network"
        address_object_value: '10.0.0.0/16'
        address_object_description: "SECNET HQ Network"
        address_object_tag: 'INTERNAL'
            
      - address_object_name: "hqfw1.secnetwork.org"
        address_object_value: '10.0.11.11'
        address_object_description: "hqfw1.secnetwork.org"
        address_object_tag: 'SECNET-MGT'

      - address_object_name: "RFC1918 - 10.0.0.0"
        address_object_value: '10.0.0.0/8'
        address_object_description: "RFC1918 - 10.0.0.0"
        address_object_tag: 'Unauthorized Traffic'
      - address_object_name: "RFC1918 - 172.16.0.0"
        address_object_value: '172.16.0.0/12'
        address_object_description: "RFC1918 - 172.16.0.0"
        address_object_tag: 'Unauthorized Traffic'
      - address_object_name: "RFC1918 - 192.168.0.0"
        address_object_value: '192.168.0.0/16'
        address_object_description: "RFC1918 - 192.168.0.0"
        address_object_tag: 'Unauthorized Traffic'

      - address_object_name: "hqdns1.secnetwork.org"
        address_object_value: '10.0.51.11'
        address_object_description: "hqdns1.secnetwork.org"
        address_object_tag: 'SECNET-SRV'

      - address_object_name: "hqdns2.secnetwork.org"
        address_object_value: '10.0.51.12'
        address_object_description: "hqdns2.secnetwork.org"
        address_object_tag: 'SECNET-SRV'

      - address_object_name: "hqntp1.secnetwork.org"
        address_object_value: '10.0.51.21'
        address_object_description: "hqdns1.secnetwork.org"
        address_object_tag: 'SECNET-SRV'

      - address_object_name: "hqntp2.secnetwork.org"
        address_object_value: '10.0.51.22'
        address_object_description: "hqdns2.secnetwork.org"
        address_object_tag: 'SECNET-SRV'

    create_address_group:
      - address_group_name: 'RFC1918'
        address_group_static_value: ['RFC1918 - 10.0.0.0','RFC1918 - 172.16.0.0','RFC1918 - 192.168.0.0']
        address_group_tag: 'Unauthorized Traffic'

      - address_group_name: 'DNS Servers'
        address_group_static_value: ['hqdns1.secnetwork.org','hqdns2.secnetwork.org']
        address_group_tag: 'SECNET-SRV'

      - address_group_name: 'NTP Servers'
        address_group_static_value: ['hqntp1.secnetwork.org','hqntp2.secnetwork.org']
        address_group_tag: 'SECNET-SRV'

  tasks:
    - name: Import Credentials from File
      include_vars: '/home/p0001/ansible/fw'
      no_log: 'yes'

    - name: Creating Address Object
      panos_address_object:
        provider: '{{ provider }}'
        name: '{{ item.address_object_name }}'
        value: '{{ item.address_object_value }}'
        description: '{{ item.address_object_description }}'
        tag: ['{{ item.address_object_tag }}']
      with_items: '{{ create_address_object }}'

    - name: Creating Address Group
      panos_address_group:
        provider: '{{ provider }}'
        name: '{{ item.address_group_name }}'
        static_value: '{{ item.address_group_static_value }}'
        tag: ['{{ item.address_group_tag }}']
      with_items: '{{ create_address_group }}'
