---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

  tasks:
    - name: Default NAT Policy - MGT
      panos_nat_rule2:
        provider: '{{ provider }}'
        name: 'Default NAT Policy - MGT'
        description: 'Default NAT Policy - MGT'
        tags: ['Management']
        nat_type: 'ipv4'
        from_zones: ['L3-Management']
        to_zones: ['L3-WAN']
        to_interface: 'vlan.9999'
        service: 'any'
        source_addresses: ['ZONE_L3-Management']
        destination_addresses: ['any']
        source_translation_type: 'dynamic-ip-and-port'
        source_translation_address_type: 'interface-address'
        source_translation_interface: 'vlan.9999'
        source_translation_ip_address: '96.231.240.210/24'