---

- name: Updating NTP Client Configuration
  hosts: 'all:!dns'
  become: true

  tasks:

    - name: Copying NTP Configuration File
      copy:
        src: ../files/chrony.conf
        dest: /etc/chrony.conf
        backup: yes

    - name: Restarting chronyd
      systemd:
        name: chronyd
        state: restarted
