---
- hosts: linux 
  become: true

  tasks:
    - name: Copying CheckMK Agent
      copy:
        src: ../../files/agents/check-mk-agent-2.1.0p19-1.noarch.rpm
        dest: /root/check-mk-agent-2.1.0p19-1.noarch.rpm
        force: no    

    - name: Install CheckMK Agent
      dnf:
        name: /root/check-mk-agent-2.1.0p19-1.noarch.rpm
        state: installed

    - name: Registering Agent
      command: "cmk-agent-ctl register --hostname '{{ ansible_hostname }}'.secnetwork.org --server hqmon1.secnetwork.org --site secnet --user automation --password 'DAANKAXXMWQSIYTDNLAV'"