---

- name: "Netbox Devices Manufacturers"
  connection: local
  hosts: localhost
  gather_facts: False

  collections:
    - netbox.netbox

  vars:
    create_manufacturers:
      - create_manufacturers_name: "CyberPower"
      - create_manufacturers_name: "Dell EMC"
      - create_manufacturers_name: "Generic"
      - create_manufacturers_name: "Palo Alto Networks"
      - create_manufacturers_name: "Synology"
      - create_manufacturers_name: "Ubiquiti"
      - create_manufacturers_name: "Apple"
      - create_manufacturers_name: "Microsoft"
      - create_manufacturers_name: "Rocky Linux"
      - create_manufacturers_name: "VMware"

  tasks:
    - name: Creating Manufacturers
      netbox_manufacturer:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: '{{ item.create_manufacturers_name }}'
        state: present
      with_items: '{{ create_manufacturers }}'
