---

- name: "Netbox Devices Manufacturers"
  connection: local
  hosts: localhost
  gather_facts: False

  collections:
    - netbox.netbox

  vars:
    create_manufacturers:
      - create_manufacturers_name: "Palo Alto Networks"

    create_device_types:
      - create_device_types_model: Switch Aggregation
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: USW-Aggregation
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Switch Lite 16 PoE
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: USW-Lite-16-PoE
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Switch Pro 24 PoE
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: USW-Pro-24-PoE
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Switch Pro 48 PoE
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: USW-Pro-48-PoE
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Switch Pro Aggregation
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: USW-Pro-Aggregation
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent    

      - create_device_types_model: Cloud Key Gen2 Plus
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UCK-G2-PLUS
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent        

      - create_device_types_model: Switch Flex Mini
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: USW-Flex-Mini
        create_device_types_u_height: 0
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Network Video Recorder
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UNVR
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: G4 Doorbell
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UVC-G4-Doorbell-US
        create_device_types_u_height: 0
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Camera G4 Pro
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UVC-G4-PRO
        create_device_types_u_height: 0
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Camera AI 360
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UVC-AI-360
        create_device_types_u_height: 0
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Access Point FlexHD
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UAP-FlexHD-US
        create_device_types_u_height: 0
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Access Point AC Mesh
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UAP-AC-M-US
        create_device_types_u_height: 0
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Access Point BeaconHD
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UAP-BeaconHD-US
        create_device_types_u_height: 0
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: Access Point In-Wall HD
        create_device_types_manufacturer: Ubiquiti
        create_device_types_part_number: UAP-IW-HD-US
        create_device_types_u_height: 0
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

    create_device_role:
      - create_device_role_name: Firewall
        create_device_role_color: 800000
        create_device_role_vm_role: false

    device_interface_template:
      - create_interface_name: Management
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: true

      - create_interface_name: ethernet1/1
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/2
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/3
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false        

      - create_interface_name: ethernet1/4
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false 

      - create_interface_name: ethernet1/5
        create_device_type: PA 850
        create_interface_type: SFP (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/6
        create_device_type: PA 850
        create_interface_type: SFP (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/7
        create_device_type: PA 850
        create_interface_type: SFP (1GE)
        create_mgmt_only: false        

      - create_interface_name: ethernet1/8
        create_device_type: PA 850
        create_interface_type: SFP (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/9
        create_device_type: PA 850
        create_interface_type: SFP+ (10GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/10
        create_device_type: PA 850
        create_interface_type: SFP+ (10GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/11
        create_device_type: PA 850
        create_interface_type: SFP+ (10GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/12
        create_device_type: PA 850
        create_interface_type: SFP+ (10GE)
        create_mgmt_only: false

      - create_interface_name: Management
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: true

      - create_interface_name: ethernet1/1
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/2
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/3
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/4
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false        

      - create_interface_name: ethernet1/5
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/6
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/7
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

  tasks:
    - name: Creating Manufacturers
      netbox_manufacturer:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: '{{ item.create_manufacturers_name }}'
        state: present
      with_items: '{{ create_manufacturers }}'

    - name: Create Device Role
      netbox_device_role:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: "{{ item.create_device_role_name }}"
          color: '{{ item.create_device_role_color }}'
          vm_role: '{{ item.create_device_role_vm_role }}'
        state: present
      with_items: '{{ create_device_role }}'

    - name: Creating Device Types
      netbox_device_type:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          model: '{{ item.create_device_types_model }}'
          manufacturer: '{{ item.create_device_types_manufacturer }}'
          part_number: '{{ item.create_device_types_part_number }}'
          u_height: '{{ item.create_device_types_u_height }}'
          is_full_depth: '{{ item.create_device_types_is_full_depth }}'
          subdevice_role: '{{ item.create_device_types_subdevice_role }}'
        state: present
      with_items: '{{ create_device_types }}'

    - name: Create Platform PAN-OS 10.2.0
      netbox_platform:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: PAN-OS 10.2.0
          manufacturer: Palo Alto Networks
        state: present

    - name: Create PAN-PA-850 Interface Template
      netbox_device_interface_template:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          device_type: '{{ item.create_device_type }}'
          name: '{{ item.create_interface_name }}'
          type: '{{ item.create_interface_type }}'
          mgmt_only: '{{ item.create_mgmt_only }}'
        state: present
      with_items: '{{ device_interface_template }}'