---

- name: "Netbox Devices Device Types"
  connection: local
  hosts: localhost
  gather_facts: False

  collections:
    - netbox.netbox

  tasks:
    - name: Create Device Role
      netbox_device_role:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: "{{ item.create_device_role_name }}"
          color: '{{ item.create_device_role_color }}'
          vm_role: '{{ item.create_device_role_vm_role }}'
        state: present
      with_items: '{{ create_device_role }}'
