---

- name: "Netbox Devices Manufacturers"
  connection: local
  hosts: localhost
  gather_facts: False

  collections:
    - netbox.netbox

  vars:
    create_manufacturers:
      - create_manufacturers_name: "Palo Alto Networks"

    create_device_types:
      - create_device_types_model: PA 850
        create_device_types_manufacturer: Palo Alto Networks
        create_device_types_part_number: PA 850
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

      - create_device_types_model: PA 250
        create_device_types_manufacturer: Palo Alto Networks
        create_device_types_part_number: PA 250
        create_device_types_u_height: 1
        create_device_types_is_full_depth: False
        create_device_types_subdevice_role: parent

    create_device_role:
      - create_device_role_name: Firewall
        create_device_role_color: 800000
        create_device_role_vm_role: false

    device_interface_template:
      - create_interface_name: Management
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: true

      - create_interface_name: ethernet1/1
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/2
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/3
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false        

      - create_interface_name: ethernet1/4
        create_device_type: PA 850
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false 

      - create_interface_name: ethernet1/5
        create_device_type: PA 850
        create_interface_type: SFP (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/6
        create_device_type: PA 850
        create_interface_type: SFP (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/7
        create_device_type: PA 850
        create_interface_type: SFP (1GE)
        create_mgmt_only: false        

      - create_interface_name: ethernet1/8
        create_device_type: PA 850
        create_interface_type: SFP (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/9
        create_device_type: PA 850
        create_interface_type: SFP+ (10GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/10
        create_device_type: PA 850
        create_interface_type: SFP+ (10GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/11
        create_device_type: PA 850
        create_interface_type: SFP+ (10GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/12
        create_device_type: PA 850
        create_interface_type: SFP+ (10GE)
        create_mgmt_only: false

      - create_interface_name: Management
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: true

      - create_interface_name: ethernet1/1
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/2
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/3
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/4
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false        

      - create_interface_name: ethernet1/5
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/6
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

      - create_interface_name: ethernet1/7
        create_device_type: PA 250
        create_interface_type: 1000BASE-T (1GE)
        create_mgmt_only: false

    device_interface:
      - device_interface_name: ethernet1/9
        device_interface_device: hqcrfw1.secnetwork.org
        device_interface_type: SFP+ (10GE)
        device_interface_lag: ae1
        device_interface_mode: Tagged (All)
        device_interface_untagged_vlan: Native

      - device_interface_name: ethernet1/10
        device_interface_device: hqcrfw1.secnetwork.org
        device_interface_type: SFP+ (10GE)
        device_interface_lag: ae1
        device_interface_mode: Tagged (All)
        device_interface_untagged_vlan: Native

      - device_interface_name: ethernet1/11
        device_interface_device: hqcrfw1.secnetwork.org
        device_interface_type: SFP+ (10GE)
        device_interface_lag: ae1
        device_interface_mode: Tagged (All)
        device_interface_untagged_vlan: Native

      - device_interface_name: ethernet1/12
        device_interface_device: hqcrfw1.secnetwork.org
        device_interface_type: SFP+ (10GE)        
        device_interface_lag: ae1
        device_interface_mode: Tagged (All)
        device_interface_untagged_vlan: Native

    create_device_interface:
      - create_device_interface_name: ae1.11
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: 11

      - create_device_interface_name: ae1.15
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Admins

      - create_device_interface_name: ae1.21
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: vManagement

      - create_device_interface_name: ae1.31
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: PDC

      - create_device_interface_name: ae1.32
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: PKI

      - create_device_interface_name: ae1.33
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: NAC

      - create_device_interface_name: ae1.34
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: SSO

      - create_device_interface_name: ae1.41
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: LOG        

      - create_device_interface_name: ae1.42
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: VAS

      - create_device_interface_name: ae1.43
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: MON

      - create_device_interface_name: ae1.44
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: NVR

      - create_device_interface_name: ae1.51
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Servers

      - create_device_interface_name: ae1.91
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Frontend

      - create_device_interface_name: ae1.95
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Backend

      - create_device_interface_name: ae1.111
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Users

      - create_device_interface_name: ae1.121
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Printers

      - create_device_interface_name: ae1.131
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Phones

      - create_device_interface_name: ae1.141
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: IOT

      - create_device_interface_name: ae1.666
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Guest

      - create_device_interface_name: ae1.1311
        create_device_interface_device: hqcrfw1.secnetwork.org
        create_device_interface_type: Virtual
        create_device_interface_parent_interface: ae1
        create_device_interface_mode: Access
        create_device_interface_untagged_vlan: Project-R
        
  tasks:
    - name: Creating Manufacturers
      netbox_manufacturer:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: '{{ item.create_manufacturers_name }}'
        state: present
      with_items: '{{ create_manufacturers }}'

    - name: Create Device Role
      netbox_device_role:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: "{{ item.create_device_role_name }}"
          color: '{{ item.create_device_role_color }}'
          vm_role: '{{ item.create_device_role_vm_role }}'
        state: present
      with_items: '{{ create_device_role }}'

    - name: Creating Device Types
      netbox_device_type:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          model: '{{ item.create_device_types_model }}'
          manufacturer: '{{ item.create_device_types_manufacturer }}'
          part_number: '{{ item.create_device_types_part_number }}'
          u_height: '{{ item.create_device_types_u_height }}'
          is_full_depth: '{{ item.create_device_types_is_full_depth }}'
          subdevice_role: '{{ item.create_device_types_subdevice_role }}'
        state: present
      with_items: '{{ create_device_types }}'

    - name: Create Platform PAN-OS 10.2.0
      netbox_platform:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: PAN-OS 10.2.0
          manufacturer: Palo Alto Networks
        state: present

    - name: Create PAN-PA-850 Interfaces
      netbox_device_interface_template:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          device_type: '{{ item.create_device_type }}'
          name: '{{ item.create_interface_name }}'
          type: '{{ item.create_interface_type }}'
          mgmt_only: '{{ item.create_mgmt_only }}'
        state: present
      with_items: '{{ device_interface_template }}'

    - name: Create Device HQCRFW1
      netbox_device:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: hqcrfw1.secnetwork.org
          device_type: PA 850
          device_role: Firewall
          site: SECNET HQ
          face: Front
          location: Server Room
          position: 48
          rack: Primary Rack
          tenant: secnet
          platform: PAN-OS 10.2.0
          primary_ip4: 10.0.11.11
        state: present

    - name: Create Internal LAG Interface 
      netbox_device_interface:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          device: hqcrfw1.secnetwork.org
          name: ae1
          type: Link Aggregation Group (LAG)
          mtu: 1500
          mgmt_only: false
          mode: Tagged (All)
          untagged_vlan:
            name: Native
            site: SECNET HQ
        state: present

    - name: Update PAN-PA-850 Interfaces
      netbox_device_interface:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          device: '{{ item.device_interface_device }}'
          name: '{{ item.device_interface_name }}'
          mode: '{{ item.device_interface_mode }}'
          untagged_vlan: '{{ item.device_interface_untagged_vlan }}'       
          lag:
            name: '{{ item.device_interface_lag }}'             
        state: present
      with_items: '{{ device_interface }}'

    - name: Create PAN-PA-850 VLAN Interfaces
      netbox_device_interface:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          device: '{{ item.create_device_interface_device }}'
          name: '{{ item.create_device_interface_name }}'
          type: '{{ item.create_device_interface_type }}'
          parent_interface: '{{ item.create_device_interface_parent_interface }}'
          mode: '{{ item.create_device_interface_mode }}'
          untagged_vlan: '{{ item.create_device_interface_untagged_vlan }}'       
        state: present
      with_items: '{{ create_device_interface }}' 

    - name: Create PAN-PA-850 IP address MGT
      netbox_ip_address:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          address: 10.0.11.11
          tenant: secnet
          status: active
          assigned_object:
            name: Management
            device: hqcrfw1.secnetwork.org
          dns_name: hqcrfw1.secnetwork.org
        state: present

    - name: Create PAN-PA-850 IP address MGT VLAN
      netbox_ip_address:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          address: 10.0.11.1
          tenant: secnet
          status: active
          assigned_object:
            name: ae1.11
            device: hqcrfw1.secnetwork.org
          dns_name: hqcrfw1-mgt.secnetwork.org                     
        state: present

    - name: Create PAN-PA-850 IP address Admins VLAN
      netbox_ip_address:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          address: 10.0.15.1
          tenant: secnet
          status: active
          assigned_object:
            name: ae1.15
            device: hqcrfw1.secnetwork.org
          dns_name: hqcrfw1-admins.secnetwork.org                     
        state: present