---

- name: "Netbox IPAM Prefixes"
  connection: local
  hosts: localhost
  gather_facts: False

  collections:
    - netbox.netbox
  
  tasks:
    - name: Create IP address with several specified options
      netbox_ip_address:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          address: 96.231.240.2
          tenant: secnet
          status: Reserved
          role: Loopback
        state: present