---

- name: "Netbox Organaization Locations"
  connection: local
  hosts: localhost
  gather_facts: False

  collections:
    - netbox.netbox

  tasks:
    - name: Create Location - Server Room
      netbox.netbox.netbox_location:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: Server Room
          site: SECNET HQ
        state: present

    - name: Create Location - Studio
      netbox.netbox.netbox_location:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: Studio
          site: SECNET HQ
        state: present

    - name: Create Location - Office
      netbox.netbox.netbox_location:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: Office
          site: SECNET HQ
        state: present

    - name: Create Location - Living Room
      netbox.netbox.netbox_location:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: Living Room
          site: SECNET HQ
        state: present

    - name: Create Location - Basement
      netbox.netbox.netbox_location:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: Basement
          site: SECNET HQ
        state: present