
---

- name: "Netbox Organization Regions"
  connection: local
  hosts: localhost
  gather_facts: False

  collections:
    - netbox.netbox

  tasks:
    - name: Create Region DMV
      netbox.netbox.netbox_region:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: DMV
        state: present    
