---

- name: "Netbox Organization Tenant"
  connection: local
  hosts: localhost
  gather_facts: False

  collections:
    - netbox.netbox

  tasks:
    - name: Create SECNET Tenant
      netbox_tenant:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: 'Secured Enterprise Core Network'
          slug: secnet
        state: present