---

- name: Updating NTP Client Configuration
  hosts: 'linux'
  become: true

  tasks:
    - name: Configuring Trunk Interface
      nmcli:
        conn_name: ens35
        ifname: ens35
        type: ethernet
        method4: disabled
        method6: disabled 
        state: present

    - name: Creating VLAN_141-IOT Interface
      nmcli:
        conn_name: VLAN_141-IOT
        ifname: ens35.141
        type: vlan
        vlanid: 141
        vlandev: ens35
        method4: disabled
        method6: disabled
        state: present