---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    aggregate_group_name: "ae1"
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_management_profile:
      - create_mgt_profile_name: 'Management'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: yes
        create_mgt_profile_ssh: yes
        create_mgt_profile_snmp: yes
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: no
        create_mgt_profile_userid_syslog_listener_ssl: no 
        create_mgt_profile_userid_syslog_listener_udp: no

      - create_mgt_profile_name: 'Default'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: no
        create_mgt_profile_ssh: no
        create_mgt_profile_snmp: no
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: no
        create_mgt_profile_userid_syslog_listener_ssl: no
        create_mgt_profile_userid_syslog_listener_udp: no

      - create_mgt_profile_name: 'Users'
        create_mgt_profile_ping: yes
        create_mgt_profile_https: no
        create_mgt_profile_ssh: no
        create_mgt_profile_snmp: no
        create_mgt_profile_response_pages: yes
        create_mgt_profile_userid_service: yes
        create_mgt_profile_userid_syslog_listener_ssl: no
        create_mgt_profile_userid_syslog_listener_udp: no

    create_aggregate_interface:
      - if_name: "ethernet1/11"
      - if_name: "ethernet1/12"

    create_vlans:
      - name: '{{ aggregate_group_name }}.11'
        tag: "11"
        enable_dhcp: "false"
        management_profile: 'Management'
        ip: ["10.0.11.1/24"]
        zone_name: "SECNET-MGT"
      - name: '{{ aggregate_group_name }}.21'
        tag: "21"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.21.1/24"]
        zone_name: "SECNET-DMZ"
      - name: '{{ aggregate_group_name }}.31'
        tag: "31"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.31.1/24"]
        zone_name: "SECNET-AAA"
      - name: '{{ aggregate_group_name }}.41'
        tag: "41"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.41.1/24"]
        zone_name: "SECNET-SEC"
      - name: '{{ aggregate_group_name }}.51'
        tag: "51"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.51.1/24"]
        zone_name: "SECNET-SRV"
      - name: '{{ aggregate_group_name }}.61'
        tag: "61"
        enable_dhcp: "false"
        management_profile: 'Default'
        ip: ["10.0.61.1/24"]
        zone_name: "SECNET-VRT"
      - name: '{{ aggregate_group_name }}.71'
        tag: "71"
        enable_dhcp: "false"
        management_profile: 'Management'
        ip: ["10.0.71.1/24"]
        zone_name: "SECNET-ADM"
      - name: '{{ aggregate_group_name }}.100'
        tag: "101"
        enable_dhcp: "false"
        management_profile: 'Users'
        ip: ["10.0.100.1/24"]
        zone_name: "SECNET-USR"

  tasks:
    - name: Import Credentials from File
      include_vars: '/home/p0001/ansible/fw'
      no_log: 'yes'

    - name: Create Interface Management Profile
      panos_management_profile:
        provider: '{{ provider }}'
        name: '{{ item.create_mgt_profile_name }}'
        ping: '{{ item.create_mgt_profile_ping }}'
        https: '{{ item.create_mgt_profile_https }}'
        ssh: '{{ item.create_mgt_profile_ssh }}'
        snmp: '{{ item.create_mgt_profile_snmp }}'
        response_pages: '{{ item.create_mgt_profile_response_pages }}'
        userid_service: '{{ item.create_mgt_profile_userid_service}}'
        #userid_syslog_listener_ssl: '{{ item.create_mgt_profile_userid_syslog_listener_ssl }}'
        #userid_syslog_listener_udp: '{{ item.create_mgt_profile_userid_syslog_listener_udp }}'
      with_items: '{{ create_management_profile }}'

    - name: Creating Aggregate Interface
      panos_aggregate_interface:
        provider: '{{ provider }}'
        if_name: '{{ aggregate_group_name }}'
        mode: "layer3"
        vr_name: "none"
        lacp_enable: "true"
        lacp_mode: "active"

    - name: Configuring Aggregate Interfaces
      panos_interface:
        provider: '{{ provider }}'
        if_name: '{{ item.if_name }}'
        mode: "aggregate-group"
        aggregate_group: '{{ aggregate_group_name }}'
      with_items: '{{ create_aggregate_interface }}'

    - name: Creating VLAN Subinterfaces
      panos_l3_subinterface:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        tag: '{{ item.tag }}'
        enable_dhcp: '{{ item.enable_dhcp }}'
        management_profile: '{{ item.management_profile }}'
        ip: '{{ item.ip }}'
        zone_name: '{{ item.zone_name }}'
      with_items: '{{ create_vlans }}'

    - name: Configuring WAN Interface
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/1"
        mode: "layer3"
        ip: ["96.231.240.217/24"]
        enable_dhcp: false
        zone_name: "WAN"
