---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

  tasks:
    - name: Import Credentials from File
      include_vars: '/home/p0001/ansible/fw'
      no_log: 'yes'

    - name: Prevent RFC1918 to WAN
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'Prevent RFC1918 to WAN'
        description: 'Prevent RFC1918 to WAN'
        tag_name: ['Unauthorized Traffic']
        group_tag: 'Unauthorized Traffic'
        source_zone: ['SECNET-AAA','SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['any']
        source_user: ['any']
        destination_zone: ['WAN']
        destination_ip: ['RFC1918']
        application: ['any']
        service: ['any']
        category: ['any']
        #log_setting: ''
        action: 'deny'
        log_start: 'yes'
        log_end: 'no'
        location: 'top'

    - name: PANOS FW - WEB-SSL
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'PANOS FW - WEB-SSL'
        rule_type: intrazone
        description: 'PANOS FW - WEB-SSL'
        tag_name: ['OUTBOUND']
        group_tag: 'Firewall Services'
        source_zone: ['WAN']
        source_ip: ['HQFW1 NAT IP']
        #source_user: ['any']
        destination_zone: ['WAN']
        destination_ip: ['US']
        application: ['web-browsing','ssl']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'Prevent RFC1918 to WAN'

    - name: PANOS FW - PANOS
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'PANOS FW - PANOS'
        rule_type: intrazone
        description: 'PANOS FW - PANOS'
        tag_name: ['OUTBOUND']
        group_tag: 'Firewall Services'
        source_zone: ['WAN']
        source_ip: ['HQFW1 NAT IP']
        #source_user: ['any']
        destination_zone: ['WAN']
        destination_ip: ['US']
        application: ['paloalto-dns-security','paloalto-updates','paloalto-wildfire-cloud','pan-db-cloud']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'PANOS FW - WEB-SSL'

    - name: PANOS FW to DNS Servers
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'PANOS FW to DNS Servers'
        rule_type: intrazone
        description: 'PANOS FW to DNS Servers'
        tag_name: ['INTERNAL']
        group_tag: 'Firewall Services'
        source_zone: ['SECNET-SRV']
        source_ip: ['10.0.51.1']
        source_user: ['any']
        destination_zone: ['SECNET-SRV']
        destination_ip: ['DNS Servers']
        application: ['dns']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'PANOS FW - PANOS'

    - name: PANOS FW to NTP Servers
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'PANOS FW to NTP Servers'
        rule_type: intrazone
        description: 'PANOS FW to NTP Servers'
        tag_name: ['INTERNAL']
        group_tag: 'Firewall Services'
        source_zone: ['SECNET-SRV']
        source_ip: ['10.0.51.1']
        source_user: ['any']
        destination_zone: ['SECNET-SRV']
        destination_ip: ['NTP Servers']
        application: ['ntp']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'PANOS FW to DNS Servers'

    - name: PANOS FW to PDC - MS-WMI
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'PANOS FW to PDC - MS-WMI'
        rule_type: intrazone
        description: 'PANOS FW to PDC - MS-WMI'
        tag_name: ['INTERNAL']
        group_tag: 'Firewall Services'
        source_zone: ['SECNET-AAA']
        source_ip: ['10.0.31.1']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['ms-wmi']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'PANOS FW to NTP Servers'

    - name: PANOS FW to Syslog
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'PANOS FW to HQLOG Syslog'
        rule_type: intrazone
        description: 'PANOS FW to HQLOG Syslog'
        tag_name: ['INTERNAL']
        group_tag: 'Firewall Services'
        source_zone: ['SECNET-SEC']
        source_ip: ['10.0.41.1']
        source_user: ['any']
        destination_zone: ['SECNET-SEC']
        destination_ip: ['hqlog.secnetwork.org']
        application: ['syslog']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'PANOS FW to PDC - MS-WMI' 

    - name: Default Deny Policy
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'Default Deny Policy'
        rule_type: 'universal'
        description: 'Default Deny Policy'
        tag_name: ['Unauthorized Traffic']
        group_tag: 'Unauthorized Traffic'
        source_zone: ['any']
        source_ip: ['any']
        source_user: ['any']
        destination_zone: ['any']
        destination_ip: ['any']
        application: ['any']
        service: ['any']
        category: ['any']
        #log_setting: ''
        action: 'deny'
        log_start: 'yes'
        log_end: 'no'
        location: 'bottom'