---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_snat_policy:
      - nat_rule_name: TEST2
        nat_rule_source_zone: SECNET-DMZ
        nat_rule_dest_zone: WAN
        nat_rule_source_ip: 10.0.0.0/24
        nat_rule_dest_ip: any
        nat_rule_snat_ip: 96.231.240.217
        nat_rule_tag: "OUTBOUND"
        nat_rule_group_tag: "OUTBOUND"

      - nat_rule_name: TEST
        nat_rule_source_zone: SECNET-MGT
        nat_rule_dest_zone: WAN
        nat_rule_source_ip: 10.0.0.0/24
        nat_rule_dest_ip: any
        nat_rule_snat_ip: 96.231.240.217
        nat_rule_tag: "OUTBOUND"
        nat_rule_group_tag: "OUTBOUND"

  tasks:
    - name: Import Credentials from File
      include_vars: '/home/p0001/ansible/fw'
      no_log: 'yes'

    - name: Get a list of all security rules
      panos_nat_rule_facts:
        provider: '{{ provider }}'
        listing: true
      register: sec_rules

    - debug:
        msg: '{{ sec_rules.listing }}'

    - name: Creating SNAT Policy
      panos_nat_rule:
        provider: '{{ provider }}'
        rule_name: '{{ item.nat_rule_name }}'
        source_zone: ['{{ item.nat_rule_source_zone }}']
        destination_zone: '{{ item.nat_rule_dest_zone }}'
        source_ip: ['{{ item.nat_rule_source_ip }}']
        destination_ip: ['{{ item.nat_rule_dest_ip }}']
        service: 'any'
        snat_type: 'static-ip'
        snat_interface: ['ethernet1/1']
        snat_static_address: '{{ item.nat_rule_snat_ip }}'
        snat_bidirectional: 'true'
        tag: ['{{ item.nat_rule_tag }}']	
        group_tag: '{{ item.nat_rule_group_tag }}'
      with_items: '{{ create_snat_policy }}'
