---

- hosts: pdc
  gather_facts: no

  collections:
    - community.windows

  vars:
    create_dns_record:

      - win_dns_record_name: "hqpdc2.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.31.12"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "12.31"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqpdc2.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqcrfw1.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.251"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "251.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqfw1.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqunifi.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.241"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "241.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqunifi.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh1.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.101"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "101.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh1.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh1-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.101"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "101.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh1-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh11.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.111"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "111.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh11.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh11-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.111"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "111.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh11-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh12.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.112"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "112.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh12.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh12-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.112"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "112.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh12-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh13.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.113"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "113.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh13.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh13-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.113"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "113.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh13-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh14.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.114"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "114.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh14.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh14-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.114"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "114.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh14-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvca.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.11"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "11.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvca.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqups1.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.91"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "91.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqups1.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqups2.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.92"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "92.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqups2.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqups3.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.93"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "93.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqups3.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqups4.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.94"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "94.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqups4.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqups5.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.95"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "95.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqups5.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqups6.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.96"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "96.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqups6.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqhsm1.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.32.11"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "11.32"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqhsm1.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqhsm2.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.32.12"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "12.32"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqhsm2.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqproxy1.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.95.11"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "11.95"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqproxy.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

  tasks:
    - name: Creating DNS Record
      win_dns_record:
        name: '{{ item.win_dns_record_name }}'
        type: '{{ item.win_dns_record_type }}'
        value: '{{ item.win_dns_record_value }}'
        zone: '{{ item.win_dns_record_zone }}'
      with_items: '{{ create_dns_record }}'

    - name: Creating PKI Record
      win_dns_record:
        name: 'pki'
        type: 'CNAME'
        value: 'hqproxy1.secnetwork.org'
        zone: 'secnetwork.org'