---

- hosts: pdc
  gather_facts: no

  collections:
    - community.windows

  vars:
    create_dns_record:
      - win_dns_record_name: "hqvh1.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.101"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "101.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh1.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh1-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.101"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "101.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh1-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh11.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.111"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "111.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh11.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh11-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.111"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "111.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh11-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh12.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.112"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "112.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh12.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh12-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.112"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "112.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh12-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh13.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.113"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "113.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh13.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh13-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.113"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "113.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh13-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

      - win_dns_record_name: "hqvh14.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.21.114"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "114.21"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh14.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"
      - win_dns_record_name: "hqvh14-idrac.secnetwork.org."
        win_dns_record_type: "A"
        win_dns_record_value: "10.0.11.114"
        win_dns_record_zone: "secnetwork.org"
      - win_dns_record_name: "114.11"
        win_dns_record_type: "PTR"
        win_dns_record_value: "hqvh14-idrac.secnetwork.org."
        win_dns_record_zone: "0.10.in-addr.arpa"

  tasks:
    - name: Creating DNS Record
      win_dns_record:
        name: '{{ item.win_dns_record_name }}'
        type: '{{ item.win_dns_record_type }}'
        value: '{{ item.win_dns_record_value }}'
        zone: '{{ item.win_dns_record_zone }}'
      with_items: '{{ create_dns_record }}'
