---
- hosts: hqmgt
  become: true

  tasks:

    - name: Copy NGINX Repos Config File
      copy:
        src: ../files/repos.conf
        dest: /etc/nginx/conf.d/repos.conf

    - name: Permit HTTP on Firewall
      firewalld:
        port: 80/tcp
        permanent: yes
        offline: no
        state: enabled

    - name: Set SELinux HTTP permissions
      sefcontext:
        target: '/opt/repos(/.*)?'
        setype: httpd_sys_content_t
        state: present

    - name: Apply SELinux HTTP permissions
      command: restorecon -Rv /opt/repos

    - name: systemd enable nginx
      systemd:
        name: nginx
        enabled: yes

    - name: systemd start nginx
      systemd:
        name: nginx
        state: started

