---

- hosts: hqmgt
  become: true

  tasks:
    - name: Installing wget
      dnf:
        name: wget
        state: installed

    - name: Installing rsync
      dnf:
        name: rsync
        state: installed

    - name: Installing Policy Core Utils (semanage)
      dnf:
        name: policycoreutils-python-utils
        state: installed 

    - name: Installing NGINX
      dnf:
        name: nginx
        state: installed
