---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

  tasks:
    - name: Import Credentials from File
      include_vars: '/home/p0001/ansible/fw'
      no_log: 'yes'

    - name: SECNET Active Directory - AD
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - AD'
        description: 'SECNET Active Directory - AD'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['active-directory']
        service: ['application-defaults']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['{{ item.audit_comment }}']
        #group_profile: ['{{ item.group_profile }}']
        #antivirus: ['{{ item.antivirus }}']
        #vulnerability: ['{{ item.vulnerability }}']
        #spyware: ['{{ item.spyware }}']
        #url_filtering: ['{{ item.url_filtering }}']
        #file_blocking: ['{{ item.file_blocking }}']
        #data_filtering: ['{{ item.data_filtering }}']
        #wildfire_analysis: ['{{ item.wildfire_analysis }}']
        #hip_profiles: ['TEST1']
        location: 'after'
        existing_rule: 'HQVAS to SECNET'
      #with_items: '{{ inbound_security_policies }}'

    - name: SECNET Active Directory - Kerberos
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - Kerberos'
        description: 'SECNET Active Directory - Kerberos'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['kerberos']
        service: ['application-defaults']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['{{ item.audit_comment }}']
        #group_profile: ['{{ item.group_profile }}']
        #antivirus: ['{{ item.antivirus }}']
        #vulnerability: ['{{ item.vulnerability }}']
        #spyware: ['{{ item.spyware }}']
        #url_filtering: ['{{ item.url_filtering }}']
        #file_blocking: ['{{ item.file_blocking }}']
        #data_filtering: ['{{ item.data_filtering }}']
        #wildfire_analysis: ['{{ item.wildfire_analysis }}']
        #hip_profiles: ['TEST1']
        location: 'after'
        existing_rule: 'SECNET Active Directory - AD'
      #with_items: '{{ inbound_security_policies }}'

    - name: SECNET Active Directory - LDAP
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - LDAP'
        description: 'SECNET Active Directory - LDAP'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['ldap']
        service: ['application-defaults']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['{{ item.audit_comment }}']
        #group_profile: ['{{ item.group_profile }}']
        #antivirus: ['{{ item.antivirus }}']
        #vulnerability: ['{{ item.vulnerability }}']
        #spyware: ['{{ item.spyware }}']
        #url_filtering: ['{{ item.url_filtering }}']
        #file_blocking: ['{{ item.file_blocking }}']
        #data_filtering: ['{{ item.data_filtering }}']
        #wildfire_analysis: ['{{ item.wildfire_analysis }}']
        #hip_profiles: ['TEST1']
        location: 'after'
        existing_rule: 'SECNET Active Directory - Kerberos'
      #with_items: '{{ inbound_security_policies }}'
