---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

    create_tags:
      - tag_name: "Active Directory"
        tag_color: "purple"
        tag_comments: "Active Directory"

  tasks:
    - name: Import Credentials from File
      include_vars: '/home/p0001/ansible/fw'
      no_log: 'yes'

    - name: Creating Interface Tags
      panos_tag_object:
        provider: '{{ provider }}'
        name: '{{ item.tag_name }}'
        color: '{{ item.tag_color }}'
        comments: '{{ item.tag_comments }}'
      with_items: '{{ create_tags }}'
