---

- hosts: firewall
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'

  tasks:
    - name: Import Credentials from File
      include_vars: '/home/p0001/ansible/fw'
      no_log: 'yes'

    - name: SECNET Active Directory - PING
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - PING'
        description: 'SECNET Active Directory - PING'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['ping']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'HQVAS to SECNET'

    - name: SECNET Active Directory - AD
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - AD'
        description: 'SECNET Active Directory - AD'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['active-directory']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - PING'

    - name: SECNET Active Directory - Kerberos
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - Kerberos'
        description: 'SECNET Active Directory - Kerberos'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['kerberos']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - AD'

    - name: SECNET Active Directory - LDAP
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - LDAP'
        description: 'SECNET Active Directory - LDAP'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['ldap']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - Kerberos'

    - name: SECNET Active Directory - NTP
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - NTP'
        description: 'SECNET Active Directory - NTP'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['ntp','ntp-base']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - LDAP'

    - name: SECNET Active Directory - NETLOGON
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - NETLOGON'
        description: 'SECNET Active Directory - NETLOGON'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['ms-netlogon']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - NTP'

    - name: SECNET Active Directory - SMB
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - SMB'
        description: 'SECNET Active Directory - SMB'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['ms-ds-smb-base','ms-ds-smbv2','ms-ds-smbv3']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - NETLOGON'

    - name: SECNET Active Directory - NETBIOS
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - NETBIOS'
        description: 'SECNET Active Directory - NETBIOS'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['netbios-dg','netbios-ns','netbios-ss']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - SMB'

    - name: SECNET Active Directory - MSRPC
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - MSRPC'
        description: 'SECNET Active Directory - MSRPC'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['msrpc-base','ms-local-user-management','ms-local-security-management']
        service: ['application-default']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - SMB'

    - name: SECNET Active Directory - WEB-SSL
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'SECNET Active Directory - WEB-SSL'
        description: 'SECNET Active Directory - WEB-SSL'
        tag_name: ['Active Directory']
        group_tag: 'Active Directory'
        source_zone: ['SECNET-DMZ','SECNET-MGT','SECNET-SEC','SECNET-SRV','SECNET-USR','SECNET-VRT']
        source_ip: ['SECNET HQ Network']
        source_user: ['any']
        destination_zone: ['SECNET-AAA']
        destination_ip: ['Domain Controllers']
        application: ['ssl']
        service: ['service-ldap','service-ldaps']
        category: ['any']
        #log_setting: ''
        action: 'allow'
        log_start: 'no'
        log_end: 'yes'
        #audit_comment: ['']
        #group_profile: ['']
        #antivirus: ['']
        #vulnerability: ['']
        #spyware: ['']
        #url_filtering: ['']
        #file_blocking: ['']
        #data_filtering: ['']
        #wildfire_analysis: ['']
        #hip_profiles: ['']
        location: 'after'
        existing_rule: 'SECNET Active Directory - MSRPC'